#! /usr/bin/bash
#python analysis_adw.py Uniform 0 100 &
sleep 1
#python analysis_adw.py Uniform 0 500 &
sleep 1
#python analysis_adw.py Gaussian 150 10 &
sleep 1
#python analysis_adw.py Gaussian 150 50 &
sleep 1
#python analysis_adw.py Gaussian 150 100 &
sleep 1
python analysis_adw.py Cauchy 150 10 &
sleep 1
python analysis_adw.py Cauchy 150 50 &
sleep 1
python analysis_adw.py Cauchy 150 100 &
sleep 1
#python analysis_adw.py EDSD 0 100 &
sleep 1
#python analysis_adw.py EDSD 0 500 &
sleep 1
#python analysis_adw.py EDSD 0 1000 &
sleep 1
python analysis_adw.py EDSD 0 1350 &
# sleep 1
# python analysis_adw.py EDSD 0 1500 &
# sleep 1
